/*
 * DefinicionesDePrueba.h
 */

#ifndef SRC_COMUN_DEFINICIONESDEPRUEBA_H_
#define SRC_COMUN_DEFINICIONESDEPRUEBA_H_

#define CANT_CLIENTES_EN_COLA_PRUEBA 10

#endif /* SRC_COMUN_DEFINICIONESDEPRUEBA_H_ */
